const Router = require('express')
var cors = require('cors')
const router = new Router()
const UserController = require('../controllers/userContr')

//router.put('/company/edit/:id', CompanyController.updComp)
//router.post('/company', CompanyController.createCompany)
router.post('/user', UserController.createUser)
router.post('/user_client', UserController.createClient)
router.post('/auth', UserController.getLoginData)
router.post('/auth_client_log', UserController.getLoginDataClient)
console.log('router is on')
router.get('/user', cors(), UserController.getUsersRstrct)
router.get('/position', cors(), UserController.getPositions)
router.get('/user/:id', cors(), UserController.getUser)
router.get('/user_cli/:id', cors(), UserController.getClient)
router.get('/cnt_res/', cors(), UserController.cnt_res)
router.get('/cnt/:id', cors(), UserController.cntView)
router.get('/user/em/:id', cors(), UserController.getUserByEmail)
// router.delete('/ad/:id', CompanyController.delAd)

module.exports = router